FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install base system dependencies
RUN apt update
RUN apt install -y dos2unix

# Move base project files
COPY start.sh requirements.txt /
RUN chmod +x /start.sh
RUN dos2unix /start.sh

# Install python dependencies
RUN pip install -r /requirements.txt

CMD /start.sh