version: "3"
name: "rentaru"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.api
    env_file: .env.docker
    volumes:
      - ./rentaru:/app
    ports:
      - 8000:8000