# Generated by Django 4.2.6 on 2023-11-24 02:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='rental_price',
            field=models.FloatField(default=0),
        ),
    ]
