# Generated by Django 4.2.6 on 2023-11-24 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierental',
            name='client_id',
            field=models.ForeignKey(db_column='client_id', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='product.client'),
        ),
        migrations.AlterField(
            model_name='movierental',
            name='movie_id',
            field=models.ForeignKey(db_column='movie_id', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='product.movie'),
        ),
    ]
