# Generated by Django 4.2.6 on 2023-11-24 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_client_movie_rental_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_at', models.DateField()),
                ('payment_type', models.CharField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to='product.client')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_id', to='product.movie')),
            ],
        ),
    ]
